_wandb:
    value:
        cli_version: 0.22.2
        e:
            dk00eznr42kx638hzqupvhy54fqarpz8:
                apple:
                    ecpuCores: 4
                    gpuCores: 16
                    memoryGb: 24
                    name: Apple M4 Pro
                    pcpuCores: 8
                    ramTotalBytes: "25769803776"
                codePath: Bewley2 copy.ipynb
                codePathLocal: Bewley2 copy.ipynb
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "494384795648"
                        used: "110972579840"
                email: zhinghe78@gmail.com
                executable: /opt/miniconda3/envs/sml/bin/python
                git:
                    commit: 9a12634c4d9b9f2b33937f15c6c18812e7d0f026
                    remote: git@github.com:imjimmylol/SML.git
                host: chenjinghedeMacBook-Pro.local
                memory:
                    total: "25769803776"
                os: macOS-15.5-arm64-arm-64bit
                program: /Users/chenjinghe/Desktop/python-projects/SML-2/Bewley2 copy.ipynb
                python: CPython 3.10.18
                root: /Users/chenjinghe/Desktop/python-projects/SML-2
                startedAt: "2025-10-28T09:02:54.700842Z"
                writerId: dk00eznr42kx638hzqupvhy54fqarpz8
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
            "4": 3.10.18
            "5": 0.22.2
            "8":
                - 1
            "12": 0.22.2
            "13": darwin-arm64
